let dictionaryData = [
    ["ability", "способность", "Her ability to solve problems quickly is impressive.", "Её способность быстро решать проблемы впечатляет."],
    ["able", "способный", "He is able to lift heavy weights without any difficulty.", "Он способен поднимать тяжёлые веса без каких-либо затруднений."],
    ["accept", "принимать", "They decided to accept the invitation to the wedding.", "Они решили принять приглашение на свадьбу."],
    ["accident", "несчастный случай", "The car accident caused a major traffic jam.", "Дорожное происшествие вызвало серьёзную пробку."],
    ["abroad", "за границей", "She plans to study abroad next year.", "Она планирует учиться за границей в следующем году."],
    ["achieve", "достигать", "He worked hard to achieve his goals.", "Он много работал, чтобы достичь своих целей."],
    ["advantage", "преимущество", "Being bilingual is a great advantage in today's world.", "Быть билингвом — это большое преимущество в современном мире."],
    ["advertise", "рекламировать", "They advertise their products on social media.", "Они рекламируют свои продукты в социальных сетях."],
    ["advertisement", "реклама", "I saw an advertisement for a new smartphone.", "Я видел рекламу нового смартфона."],
    ["advertising", "рекламный бизнес", "Advertising plays a big role in modern marketing.", "Реклама играет большую роль в современном маркетинге."],
    ["affect", "влиять", "The weather can affect our mood.", "Погода может влиять на наше настроение."],
    ["against", "против", "He stood against the decision to close the school.", "Он выступал против решения закрыть школу."],
    ["alive", "живой", "The rescue team found him alive after the earthquake.", "Спасатели нашли его живым после землетрясения."],
    ["almost", "почти", "She almost missed the train.", "Она почти опоздала на поезд."],
    ["along", "вдоль", "We walked along the river.", "Мы шли вдоль реки."],
    ["although", "хотя", "Although it was raining, we went for a hike.", "Хотя шёл дождь, мы отправились в поход."],
    ["among", "среди", "She was popular among her classmates.", "Она была популярна среди своих одноклассников."],
    ["amount", "количество", "He needs a small amount of sugar for the recipe.", "Ему нужно небольшое количество сахара для рецепта."],
    ["ancient", "древний", "They visited the ancient ruins during their trip.", "Они посетили древние руины во время путешествия."],
    ["ankle", "лодыжка", "She twisted her ankle while jogging.", "Она подвернула лодыжку, бегая трусцой."],
    ["any more", "больше", "I don’t want any more cake, thank you.", "Я больше не хочу торт, спасибо."],
    ["anyway", "в любом случае", "It was raining, but we went to the park anyway.", "Шёл дождь, но мы всё равно пошли в парк."],
    ["anywhere", "где угодно", "I can work from anywhere with a good internet connection.", "Я могу работать откуда угодно при наличии хорошего интернета."],
    ["app", "приложение", "She downloaded a new fitness app on her phone.", "Она скачала новое приложение для фитнеса на телефон."],
    ["appear", "появляться", "A rainbow appeared after the rain.", "После дождя появилась радуга."],
    ["appearance", "внешность", "Her appearance changed a lot after the haircut.", "Её внешность сильно изменилась после стрижки."],
    ["apply", "применять", "You should apply this cream to your skin daily.", "Эту мазь нужно наносить на кожу ежедневно."],
    ["architect", "архитектор", "The architect designed a beautiful modern building.", "Архитектор спроектировал красивое современное здание."],
    ["architecture", "архитектура", "The city is known for its ancient architecture.", "Этот город известен своей древней архитектурой."],
    ["argue", "спорить", "They often argue about politics.", "Они часто спорят о политике."],
    ["argument", "аргумент", "She presented a strong argument in her favor.", "Она представила сильный аргумент в свою пользу."],
    ["army", "армия", "He joined the army when he was 18.", "Он пошёл в армию, когда ему было 18."],
    ["arrange", "организовывать", "I’ll arrange a meeting with the manager.", "Я организую встречу с менеджером."],
    ["arrangement", "договорённость", "We made an arrangement to meet at noon.", "Мы договорились встретиться в полдень."],
    ["as", "как", "He works as a teacher.", "Он работает учителем."],
    ["asleep", "спящий", "The baby is asleep in her crib.", "Ребёнок спит в своей кроватке."],
    ["assistant", "ассистент", "Her assistant helped organize the event.", "Её ассистент помог организовать мероприятие."],
    ["athlete", "спортсмен", "He is a professional athlete who competes internationally.", "Он профессиональный спортсмен, выступающий на международных соревнованиях."],
    ["attack", "атаковать", "The army decided to attack at dawn.", "Армия решила атаковать на рассвете."],
    ["attend", "посещать", "She attends a yoga class every week.", "Она посещает занятия йогой каждую неделю."],
    ["attention", "внимание", "The teacher asked for the students' attention.", "Учитель попросил внимания у учеников."],
    ["attractive", "привлекательный", "The view from the top of the mountain is very attractive.", "Вид с вершины горы очень привлекательный."],
    ["audience", "аудитория", "The audience applauded at the end of the performance.", "Аудитория аплодировала в конце выступления."],
    ["author", "автор", "She is the author of several best-selling novels.", "Она автор нескольких бестселлеров."],
    ["available", "доступный", "This product is available in different sizes.", "Этот продукт доступен в разных размерах."],
    ["average", "средний", "The average temperature in July is 25°C.", "Средняя температура в июле составляет 25°C."],
    ["avoid", "избегать", "You should avoid eating too much junk food.", "Вам следует избегать употребления слишком большого количества нездоровой пищи."],
    ["award", "награда", "He received an award for his outstanding work.", "Он получил награду за выдающуюся работу."]
        ["awful", "ужасный", "The weather today is awful.", "Сегодня ужасная погода."],
    ["back", "назад", "He turned back to check if he left something behind.", "Он вернулся, чтобы проверить, не забыл ли что-то."],
    ["background", "фон", "The photo has a beautiful mountain in the background.", "На фото красивый горный пейзаж на фоне."],
    ["badly", "плохо", "He played badly during the match.", "Он плохо сыграл во время матча."],
    ["bar", "бар", "They decided to meet at the bar after work.", "Они решили встретиться в баре после работы."],
    ["baseball", "бейсбол", "Baseball is a popular sport in the United States.", "Бейсбол — популярный вид спорта в США."],
    ["based", "основанный", "The movie is based on a true story.", "Фильм основан на реальных событиях."],
    ["basketball", "баскетбол", "He plays basketball with his friends every weekend.", "Он играет в баскетбол с друзьями каждые выходные."],
    ["bean", "боб", "I like adding green beans to my salad.", "Я люблю добавлять зелёные бобы в салат."],
    ["bear", "медведь", "We saw a bear in the forest during our hike.", "Мы видели медведя в лесу во время похода."],
    ["beat", "побеждать", "Our team managed to beat the competition.", "Наша команда сумела победить в соревновании."],
    ["beef", "говядина", "I ordered a beef steak for dinner.", "Я заказал стейк из говядины на ужин."],
    ["before", "до", "We arrived at the station before the train left.", "Мы приехали на станцию до отправления поезда."],
    ["behave", "вести себя", "Children are expected to behave well in class.", "Ожидается, что дети будут хорошо себя вести на уроке."],
    ["behaviour", "поведение", "His behaviour at the meeting was very professional.", "Его поведение на встрече было очень профессиональным."],
    ["belong", "принадлежать", "These books belong to the school library.", "Эти книги принадлежат школьной библиотеке."],
    ["belt", "пояс", "He tightened his belt before starting the hike.", "Он затянул пояс перед началом похода."],
    ["benefit", "выгода", "One benefit of exercise is better health.", "Одна из выгод занятий спортом — лучшее здоровье."]
        ["best", "лучший", "This is the best movie I’ve ever seen.", "Это лучший фильм, который я когда-либо видел."],
    ["better", "лучше", "She feels better after taking some rest.", "Она чувствует себя лучше после отдыха."],
    ["between", "между", "The park is located between the school and the hospital.", "Парк расположен между школой и больницей."],
    ["billion", "миллиард", "The company made a billion dollars in revenue last year.", "Компания заработала миллиард долларов дохода в прошлом году."],
    ["bin", "мусорное ведро", "Please put the trash in the bin.", "Пожалуйста, выбросьте мусор в ведро."],
    ["biology", "биология", "She is studying biology at the university.", "Она изучает биологию в университете."],
    ["birth", "рождение", "The birth of their first child was a joyous occasion.", "Рождение их первого ребёнка было радостным событием."],
    ["biscuit", "печенье", "I like to have a biscuit with my tea.", "Мне нравится съесть печенье с чаем."],
    ["bit", "кусочек", "Can I have a bit of chocolate?", "Можно мне кусочек шоколада?"],
    ["blank", "пустой", "Please fill in the blank spaces on the form.", "Пожалуйста, заполните пустые места в форме."],
    ["blood", "кровь", "The nurse took a sample of his blood.", "Медсестра взяла образец его крови."],
    ["blow", "дуть", "The wind started to blow harder in the evening.", "Ветер начал дуть сильнее к вечеру."],
    ["board", "доска", "The teacher wrote the lesson topic on the board.", "Учитель написал тему урока на доске."],
    ["boil", "кипятить", "You need to boil the water before making tea.", "Нужно вскипятить воду перед тем, как заварить чай."],
    ["bone", "кость", "The X-ray showed a broken bone in his arm.", "Рентген показал сломанную кость в его руке."],
    ["book", "книга", "She borrowed a book from the library.", "Она взяла книгу в библиотеке."],
    ["borrow", "брать взаймы", "Can I borrow your pen for a moment?", "Можно я возьму твою ручку на минуту?"],
];