let dictionaryData = [
    ["ability", "способность", "Her ability to solve problems quickly is impressive.", "Её способность быстро решать проблемы впечатляет."],
    ["able", "способный", "He is able to lift heavy weights without any difficulty.", "Он способен поднимать тяжёлые веса без каких-либо затруднений."],
    ["accept", "принимать", "They decided to accept the invitation to the wedding.", "Они решили принять приглашение на свадьбу."],
    ["accident", "несчастный случай", "The car accident caused a major traffic jam.", "Дорожное происшествие вызвало серьёзную пробку."],
    ["abroad", "за границей", "She plans to study abroad next year.", "Она планирует учиться за границей в следующем году."],
    ["achieve", "достигать", "He worked hard to achieve his goals.", "Он много работал, чтобы достичь своих целей."],
    ["advantage", "преимущество", "Being bilingual is a great advantage in today's world.", "Быть билингвом — это большое преимущество в современном мире."],
    ["advertise", "рекламировать", "They advertise their products on social media.", "Они рекламируют свои продукты в социальных сетях."],
    ["advertisement", "реклама", "I saw an advertisement for a new smartphone.", "Я видел рекламу нового смартфона."],
    ["advertising", "рекламный бизнес", "Advertising plays a big role in modern marketing.", "Реклама играет большую роль в современном маркетинге."],
    ["affect", "влиять", "The weather can affect our mood.", "Погода может влиять на наше настроение."],
    ["against", "против", "He stood against the decision to close the school.", "Он выступал против решения закрыть школу."],
    ["alive", "живой", "The rescue team found him alive after the earthquake.", "Спасатели нашли его живым после землетрясения."],
    ["almost", "почти", "She almost missed the train.", "Она почти опоздала на поезд."],
    ["along", "вдоль", "We walked along the river.", "Мы шли вдоль реки."],
    ["although", "хотя", "Although it was raining, we went for a hike.", "Хотя шёл дождь, мы отправились в поход."],
    ["among", "среди", "She was popular among her classmates.", "Она была популярна среди своих одноклассников."],
    ["amount", "количество", "He needs a small amount of sugar for the recipe.", "Ему нужно небольшое количество сахара для рецепта."],
    ["ancient", "древний", "They visited the ancient ruins during their trip.", "Они посетили древние руины во время путешествия."],
    ["ankle", "лодыжка", "She twisted her ankle while jogging.", "Она подвернула лодыжку, бегая трусцой."],
    ["any more", "больше", "I don’t want any more cake, thank you.", "Я больше не хочу торт, спасибо."],
    ["anyway", "в любом случае", "It was raining, but we went to the park anyway.", "Шёл дождь, но мы всё равно пошли в парк."],
    ["anywhere", "где угодно", "I can work from anywhere with a good internet connection.", "Я могу работать откуда угодно при наличии хорошего интернета."],
    ["app", "приложение", "She downloaded a new fitness app on her phone.", "Она скачала новое приложение для фитнеса на телефон."],
    ["appear", "появляться", "A rainbow appeared after the rain.", "После дождя появилась радуга."],
    ["appearance", "внешность", "Her appearance changed a lot after the haircut.", "Её внешность сильно изменилась после стрижки."],
    ["apply", "применять", "You should apply this cream to your skin daily.", "Эту мазь нужно наносить на кожу ежедневно."],
    ["architect", "архитектор", "The architect designed a beautiful modern building.", "Архитектор спроектировал красивое современное здание."],
    ["architecture", "архитектура", "The city is known for its ancient architecture.", "Этот город известен своей древней архитектурой."],
    ["argue", "спорить", "They often argue about politics.", "Они часто спорят о политике."],
    ["argument", "аргумент", "She presented a strong argument in her favor.", "Она представила сильный аргумент в свою пользу."],
    ["army", "армия", "He joined the army when he was 18.", "Он пошёл в армию, когда ему было 18."],
    ["arrange", "организовывать", "I’ll arrange a meeting with the manager.", "Я организую встречу с менеджером."],
    ["arrangement", "договорённость", "We made an arrangement to meet at noon.", "Мы договорились встретиться в полдень."],
    ["as", "как", "He works as a teacher.", "Он работает учителем."],
    ["asleep", "спящий", "The baby is asleep in her crib.", "Ребёнок спит в своей кроватке."],
    ["assistant", "ассистент", "Her assistant helped organize the event.", "Её ассистент помог организовать мероприятие."],
    ["athlete", "спортсмен", "He is a professional athlete who competes internationally.", "Он профессиональный спортсмен, выступающий на международных соревнованиях."],
    ["attack", "атаковать", "The army decided to attack at dawn.", "Армия решила атаковать на рассвете."],
    ["attend", "посещать", "She attends a yoga class every week.", "Она посещает занятия йогой каждую неделю."],
    ["attention", "внимание", "The teacher asked for the students' attention.", "Учитель попросил внимания у учеников."],
    ["attractive", "привлекательный", "The view from the top of the mountain is very attractive.", "Вид с вершины горы очень привлекательный."],
    ["audience", "аудитория", "The audience applauded at the end of the performance.", "Аудитория аплодировала в конце выступления."],
    ["author", "автор", "She is the author of several best-selling novels.", "Она автор нескольких бестселлеров."],
    ["available", "доступный", "This product is available in different sizes.", "Этот продукт доступен в разных размерах."],
    ["average", "средний", "The average temperature in July is 25°C.", "Средняя температура в июле составляет 25°C."],
    ["avoid", "избегать", "You should avoid eating too much junk food.", "Вам следует избегать употребления слишком большого количества нездоровой пищи."],
    ["award", "награда", "He received an award for his outstanding work.", "Он получил награду за выдающуюся работу."]
        ["awful", "ужасный", "The weather today is awful.", "Сегодня ужасная погода."],
    ["back", "назад", "He turned back to check if he left something behind.", "Он вернулся, чтобы проверить, не забыл ли что-то."],
    ["background", "фон", "The photo has a beautiful mountain in the background.", "На фото красивый горный пейзаж на фоне."],
    ["badly", "плохо", "He played badly during the match.", "Он плохо сыграл во время матча."],
    ["bar", "бар", "They decided to meet at the bar after work.", "Они решили встретиться в баре после работы."],
    ["baseball", "бейсбол", "Baseball is a popular sport in the United States.", "Бейсбол — популярный вид спорта в США."],
    ["based", "основанный", "The movie is based on a true story.", "Фильм основан на реальных событиях."],
    ["basketball", "баскетбол", "He plays basketball with his friends every weekend.", "Он играет в баскетбол с друзьями каждые выходные."],
    ["bean", "боб", "I like adding green beans to my salad.", "Я люблю добавлять зелёные бобы в салат."],
    ["bear", "медведь", "We saw a bear in the forest during our hike.", "Мы видели медведя в лесу во время похода."],
    ["beat", "побеждать", "Our team managed to beat the competition.", "Наша команда сумела победить в соревновании."],
    ["beef", "говядина", "I ordered a beef steak for dinner.", "Я заказал стейк из говядины на ужин."],
    ["before", "до", "We arrived at the station before the train left.", "Мы приехали на станцию до отправления поезда."],
    ["behave", "вести себя", "Children are expected to behave well in class.", "Ожидается, что дети будут хорошо себя вести на уроке."],
    ["behaviour", "поведение", "His behaviour at the meeting was very professional.", "Его поведение на встрече было очень профессиональным."],
    ["belong", "принадлежать", "These books belong to the school library.", "Эти книги принадлежат школьной библиотеке."],
    ["belt", "пояс", "He tightened his belt before starting the hike.", "Он затянул пояс перед началом похода."],
    ["benefit", "выгода", "One benefit of exercise is better health.", "Одна из выгод занятий спортом — лучшее здоровье."]
        ["best", "лучший", "This is the best movie I’ve ever seen.", "Это лучший фильм, который я когда-либо видел."],
    ["better", "лучше", "She feels better after taking some rest.", "Она чувствует себя лучше после отдыха."],
    ["between", "между", "The park is located between the school and the hospital.", "Парк расположен между школой и больницей."],
    ["billion", "миллиард", "The company made a billion dollars in revenue last year.", "Компания заработала миллиард долларов дохода в прошлом году."],
    ["bin", "мусорное ведро", "Please put the trash in the bin.", "Пожалуйста, выбросьте мусор в ведро."],
    ["biology", "биология", "She is studying biology at the university.", "Она изучает биологию в университете."],
    ["birth", "рождение", "The birth of their first child was a joyous occasion.", "Рождение их первого ребёнка было радостным событием."],
    ["biscuit", "печенье", "I like to have a biscuit with my tea.", "Мне нравится съесть печенье с чаем."],
    ["bit", "кусочек", "Can I have a bit of chocolate?", "Можно мне кусочек шоколада?"],
    ["blank", "пустой", "Please fill in the blank spaces on the form.", "Пожалуйста, заполните пустые места в форме."],
    ["blood", "кровь", "The nurse took a sample of his blood.", "Медсестра взяла образец его крови."],
    ["blow", "дуть", "The wind started to blow harder in the evening.", "Ветер начал дуть сильнее к вечеру."],
    ["board", "доска", "The teacher wrote the lesson topic on the board.", "Учитель написал тему урока на доске."],
    ["boil", "кипятить", "You need to boil the water before making tea.", "Нужно вскипятить воду перед тем, как заварить чай."],
    ["bone", "кость", "The X-ray showed a broken bone in his arm.", "Рентген показал сломанную кость в его руке."],
    ["book", "книга", "She borrowed a book from the library.", "Она взяла книгу в библиотеке."],
    ["borrow", "брать взаймы", "Can I borrow your pen for a moment?", "Можно я возьму твою ручку на минуту?"],
	
	
    ["awful", "ужасный", "The weather was awful yesterday.", "Погода была ужасной вчера."],
    ["badly", "плохо", "He danced so badly that everyone laughed.", "Он танцевал так плохо, что все смеялись."],
    ["bowl", "миска", "She filled the bowl with fresh fruit.", "Она наполнила миску свежими фруктами."],
    ["burn", "гореть", "The fire continued to burn all night.", "Огонь продолжал гореть всю ночь."],
    ["camp", "лагерь", "We stayed at a summer camp by the lake.", "Мы остановились в летнем лагере у озера."],
    ["camping", "поход с палатками", "They went camping in the mountains.", "Они отправились в поход с палатками в горы."],
    ["care", "забота", "She takes great care of her garden.", "Она очень заботится о своем саде."],
    ["catch", "ловить", "He tried to catch the ball but missed.", "Он попытался поймать мяч, но промахнулся."],
    ["cause", "причина", "The main cause of the accident was speeding.", "Главной причиной аварии было превышение скорости."],
    ["certain", "определенный", "I'm certain that he's telling the truth.", "Я уверен, что он говорит правду."],
    ["certainly", "конечно", "I will certainly help you with your homework.", "Я, конечно, помогу тебе с домашней работой."],
    ["charity", "благотворительность", "She donates to charity every month.", "Она жертвует на благотворительность каждый месяц."],
    ["chef", "шеф-повар", "The chef prepared an excellent meal.", "Шеф-повар приготовил великолепное блюдо."],
    ["chemistry", "химия", "He is studying chemistry at university.", "Он изучает химию в университете."],
	
	
    ["church", "церковь", "They go to church every Sunday.", "Они ходят в церковь каждое воскресенье."],
    ["climate", "климат", "The climate in this region is very dry.", "Климат в этом регионе очень сухой."],
    ["coach", "тренер", "The coach gave the team a motivational speech.", "Тренер произнес мотивирующую речь команде."],
    ["coast", "побережье", "They walked along the coast enjoying the view.", "Они гуляли по побережью, наслаждаясь видом."],
    ["collect", "собирать", "She likes to collect old coins.", "Она любит собирать старинные монеты."],
    ["comedy", "комедия", "We watched a hilarious comedy last night.", "Мы смотрели смешную комедию прошлой ночью."],
    ["compete", "состязаться", "Athletes from all over the world compete in the Olympics.", "Спортсмены со всего мира соревнуются на Олимпиаде."],
    ["competition", "соревнование", "The competition was tough but exciting.", "Соревнование было сложным, но захватывающим."],
    ["complain", "жаловаться", "He always complains about the weather.", "Он всегда жалуется на погоду."],
    ["completely", "полностью", "The room was completely silent.", "Комната была полностью тиха."],
    ["consider", "рассматривать", "Please consider my application for the job.", "Пожалуйста, рассмотрите мою заявку на работу."],
    ["cooker", "плита", "The cooker in their kitchen is brand new.", "Плита на их кухне совершенно новая."],
    ["cover", "покрывать", "She used a blanket to cover the baby.", "Она накрыла ребенка одеялом."],
    ["crime", "преступление", "The police are investigating the crime.", "Полиция расследует преступление."],
    ["cross", "пересекать", "Be careful when you cross the road.", "Будь осторожен, когда переходишь дорогу."],
	
	
    ["crowd", "толпа", "A large crowd gathered to watch the parade.", "Большая толпа собралась, чтобы посмотреть парад."],
    ["crowded", "переполненный", "The bus was so crowded that we could barely move.", "Автобус был настолько переполнен, что мы едва могли двигаться."],
    ["cupboard", "шкаф", "She opened the cupboard to get a plate.", "Она открыла шкаф, чтобы достать тарелку."],
    ["curly", "кудрявый", "She has beautiful curly hair.", "У нее красивые кудрявые волосы."],
    ["cycle", "велосипед", "He prefers to cycle to work every day.", "Он предпочитает ездить на велосипеде на работу каждый день."],
    ["deal", "сделка", "They made a deal to share the profits equally.", "Они заключили сделку делить прибыль поровну."],
    ["decision", "решение", "It was a difficult decision to make.", "Это было сложное решение."],
    ["deep", "глубокий", "The lake is very deep in the middle.", "Озеро очень глубокое в середине."],
    ["diary", "дневник", "She writes in her diary every evening.", "Она пишет в своем дневнике каждый вечер."],
    ["direct", "прямой", "The train offers a direct route to the city center.", "Поезд предлагает прямой маршрут в центр города."],
    ["direction", "направление", "Can you give me directions to the station?", "Можете подсказать мне дорогу к станции?"],
    ["disaster", "катастрофа", "The earthquake was a terrible disaster.", "Землетрясение было ужасной катастрофой."],
    ["discover", "обнаружить", "They discovered a hidden treasure in the cave.", "Они обнаружили спрятанное сокровище в пещере."],
    ["discovery", "открытие", "The discovery of a new planet excited the scientists.", "Открытие новой планеты взволновало ученых."],
    ["discussion", "обсуждение", "We had a long discussion about the project.", "У нас было длительное обсуждение проекта."],
    ["disease", "болезнь", "The doctor is researching a cure for the disease.", "Доктор исследует лекарство от этой болезни."],
	

["drawing", "рисунок", "She showed me a beautiful drawing of a sunset.", "Она показала мне красивый рисунок заката."],  
["dream", "мечта; сон", "Last night, I had a strange dream.", "Прошлой ночью мне приснился странный сон."],  
["dry", "сухой", "The clothes are finally dry after hanging outside.", "Одежда наконец высохла после того, как повисела на улице."],  
["earn", "зарабатывать", "She earns a good salary at her new job.", "Она зарабатывает хорошую зарплату на новой работе."],  
["effect", "эффект", "The medicine had an immediate effect.", "Лекарство оказало немедленный эффект."],  
["either", "либо; любой из двух", "You can choose either tea or coffee.", "Ты можешь выбрать либо чай, либо кофе."],  
["employ", "нанимать", "The company plans to employ more staff next year.", "Компания планирует нанять больше сотрудников в следующем году."],  
["employee", "сотрудник", "The company has over 500 employees.", "В компании работает более 500 сотрудников."],  
["employer", "работодатель", "Her employer gave her a promotion.", "Ее работодатель дал ей повышение."],  
["ending", "концовка", "The movie had a surprising ending.", "У фильма была неожиданная концовка."],  
["enormous", "огромный", "They live in an enormous house near the park.", "Они живут в огромном доме рядом с парком."],  
["equipment", "оборудование", "The gym has all the latest equipment.", "В спортзале есть все новейшее оборудование."],  
["especially", "особенно", "I love desserts, especially chocolate cake.", "Я люблю десерты, особенно шоколадный торт."],  
["essay", "сочинение", "He wrote an essay about climate change.", "Он написал сочинение об изменении климата."],  
["evidence", "доказательство", "The police found no evidence of a crime.", "Полиция не нашла доказательств преступления."],  
["exact", "точный", "Do you know the exact time of the meeting?", "Ты знаешь точное время встречи?"],  
["exactly", "точно", "That's exactly what I wanted to say.", "Это именно то, что я хотел сказать."],  
["except", "кроме", "Everyone went to the party except for him.", "Все пошли на вечеринку, кроме него."],  
["expect", "ожидать", "We expect the train to arrive on time.", "Мы ожидаем, что поезд прибудет вовремя."],  
["explanation", "объяснение", "The teacher gave a clear explanation of the problem.", "Учитель дал ясное объяснение проблемы."],  
["express", "выражать", "He found it difficult to express his feelings.", "Ему было сложно выразить свои чувства."],  
["factor", "фактор", "Hard work is a key factor in success.", "Усердная работа — ключевой фактор успеха."],  
["factory", "завод", "The factory produces thousands of cars every month.", "Завод производит тысячи автомобилей каждый месяц."],  
["fair", "справедливый", "The decision was fair to everyone involved.", "Решение было справедливым для всех участников."],  
["fall", "падать", "The leaves fall from the trees in autumn.", "Листья падают с деревьев осенью."],  


["fan", "вентилятор; поклонник", "She turned on the fan because it was hot.", "Она включила вентилятор, потому что было жарко."],  
["farm", "ферма", "They have a small farm with cows and chickens.", "У них есть маленькая ферма с коровами и курами."],  
["farming", "земледелие; фермерство", "Farming is an important industry in rural areas.", "Фермерство — важная отрасль в сельских районах."],  
["fear", "страх", "He has a fear of heights.", "Он боится высоты."],  
["feature", "особенность", "The smartphone has many new features.", "У этого смартфона много новых функций."],  
["feed", "кормить", "She went to feed the ducks at the park.", "Она пошла кормить уток в парке."],  
["fiction", "вымысел; художественная литература", "He enjoys reading science fiction novels.", "Он любит читать научно-фантастические романы."],  
["firstly", "во-первых", "Firstly, we need to gather more information.", "Во-первых, нам нужно собрать больше информации."],  
["fit", "подходить; быть в хорошей форме", "These shoes fit me perfectly.", "Эти туфли мне идеально подходят."],  
["flu", "грипп", "She caught the flu last week.", "Она заболела гриппом на прошлой неделе."],  
["flying", "полет", "Flying is the fastest way to travel.", "Полет — самый быстрый способ путешествия."],  
["following", "следующий", "Please answer the following questions.", "Пожалуйста, ответьте на следующие вопросы."],  
["foreign", "иностранный", "She speaks three foreign languages.", "Она говорит на трех иностранных языках."],  
["fork", "вилка", "He picked up the spaghetti with a fork.", "Он взял спагетти вилкой."],  
["formal", "формальный", "The event requires formal dress.", "Мероприятие требует формальной одежды."],  
["fortunately", "к счастью", "Fortunately, no one was injured in the accident.", "К счастью, никто не пострадал в аварии."],  
["fridge", "холодильник", "The milk is in the fridge.", "Молоко находится в холодильнике."],  
["further", "дальше; далее", "We need to discuss this further.", "Нам нужно обсудить это дальше."],  
["future", "будущее", "He is planning for the future.", "Он планирует будущее."],  
["gap", "разрыв; пробел", "There is a gap between the two buildings.", "Между двумя зданиями есть разрыв."],  
["greet", "приветствовать", "She greeted her guests with a warm smile.", "Она поприветствовала своих гостей теплой улыбкой."],  

["ground", "земля; почва", "The ground was wet after the rain.", "Земля была мокрой после дождя."],  
["habit", "привычка", "He has the habit of waking up early every day.", "У него есть привычка вставать рано каждый день."],  
["hall", "зал", "We met in the main hall of the building.", "Мы встретились в главном зале здания."],  
["headache", "головная боль", "She has a headache and needs to rest.", "У нее болит голова, и ей нужно отдохнуть."],  
["heart", "сердце", "Her heart was racing with excitement.", "Ее сердце билось быстрее от волнения."],  
["heat", "жара; тепло", "The heat was unbearable during the summer.", "Жара была невыносимой летом."],  
["hers", "её (принадлежность)", "The book is hers, not mine.", "Эта книга её, не моя."],  
["herself", "сама", "She did it all by herself.", "Она сделала это полностью сама."],  
["hill", "холм", "They climbed to the top of the hill.", "Они поднялись на вершину холма."],  
["hit", "ударить", "He hit the ball with a bat.", "Он ударил мяч битой."],  
["hole", "дыра", "There's a hole in my jacket.", "В моем пальто дырка."],  
["huge", "огромный", "The castle was huge and impressive.", "Замок был огромным и впечатляющим."],  
["hurt", "повредить; ранить", "She hurt her arm while playing basketball.", "Она повредила руку, играя в баскетбол."],  
["illness", "болезнь", "The doctor treated his illness with medication.", "Доктор лечил его болезнь с помощью лекарств."],  
["immediately", "немедленно", "Please call me immediately if there's an emergency.", "Пожалуйста, позвони мне немедленно, если произойдет чрезвычайная ситуация."],  
["informal", "неформальный", "The meeting was informal and relaxed.", "Встреча была неформальной и непринужденной."],  
["injury", "травма", "She suffered a serious injury in the accident.", "Она получила серьезную травму в аварии."],  
["insect", "насекомое", "An insect flew into the room through the window.", "Насекомое влетело в комнату через окно."],

["intelligent", "умный", "She is an intelligent student who always gets good grades.", "Она умная студентка, которая всегда получает хорошие оценки."],  
["introduction", "введение", "The professor gave a brief introduction to the course.", "Профессор дал краткое введение в курс."],  
["invent", "изобретать", "Thomas Edison invented the light bulb.", "Томас Эдисон изобрел электрическую лампочку."],  
["invention", "изобретение", "The telephone is one of the greatest inventions of all time.", "Телефон — одно из величайших изобретений всех времен."],  
["invitation", "приглашение", "I received an invitation to the wedding.", "Я получил приглашение на свадьбу."],  
["itself", "само; себя", "The cat groomed itself after the walk.", "Кошка вылизала себя после прогулки."],  
["jam", "джем; варенье", "She spread strawberry jam on her toast.", "Она намазала клубничное варенье на тост."],  
["jewellery", "ювелирные изделия", "She wore beautiful jewellery to the party.", "Она носила красивые ювелирные изделия на вечеринке."],  
["knee", "колено", "He injured his knee while playing football.", "Он повредил колено, играя в футбол."],  
["knock", "стучать", "Please knock on the door before entering.", "Пожалуйста, постучите в дверь перед входом."],  
["lab", "лаборатория", "The scientists conducted experiments in the lab.", "Учёные проводили эксперименты в лаборатории."],  
["lake", "озеро", "We spent the afternoon by the lake.", "Мы провели день у озера."],  
["laughter", "смех", "Her laughter filled the room.", "Ее смех наполнил комнату."],  
["law", "закон", "The law requires drivers to wear seat belts.", "Закон требует, чтобы водители пристегивались ремнями безопасности."],  
["lawyer", "адвокат", "He hired a lawyer to represent him in court.", "Он нанял адвоката, чтобы он представлял его в суде."],  
["lead", "вести", "She will lead the team on the project.", "Она будет вести команду в проекте."],  
["learning", "обучение", "Learning a new language can be challenging.", "Изучение нового языка может быть сложным."],

["least", "наименьший", "This is the least expensive option.", "Это наименее дорогой вариант."],  
["lend", "одолжить", "Can you lend me your book for a week?", "Можешь одолжить мне свою книгу на неделю?"],  
["less", "меньше", "She eats less sugar than her sister.", "Она ест меньше сахара, чем ее сестра."],  
["lift", "поднимать", "He helped me lift the heavy box.", "Он помог мне поднять тяжелую коробку."],  
["likely", "вероятно", "It's likely to rain later today.", "Вероятно, сегодня позже будет дождь."],  
["lorry", "грузовик", "The lorry is delivering goods to the store.", "Грузовик доставляет товары в магазин."],  
["lovely", "прекрасный", "We had a lovely day at the beach.", "У нас был прекрасный день на пляже."],  
["low", "низкий", "The ceiling is too low for tall people.", "Потолок слишком низкий для высоких людей."],  
["major", "основной", "She made a major contribution to the project.", "Она сделала основной вклад в проект."],  
["manner", "манера", "He speaks in a polite manner.", "Он говорит вежливо."],  
["maths", "математика", "He is very good at maths.", "Он очень хорошо умеет в математике."],  
["matter", "вопрос; вещь", "It doesn't matter if you're late.", "Не имеет значения, если ты опоздаешь."],  
["mention", "упомянуть", "She didn't mention anything about the meeting.", "Она не упомянула ничего о встрече."],  
["mine", "мой (принадлежность)", "This book is mine.", "Эта книга моя."],  
["mostly", "в основном", "She eats mostly vegetables.", "Она в основном ест овощи."],  
["movement", "движение", "The movement of the car was very smooth.", "Движение автомобиля было очень плавным."],  
["narrow", "узкий", "The street is too narrow for a large truck.", "Улица слишком узкая для большого грузовика."],

["neck", "шея", "He has a tattoo on his neck.", "У него татуировка на шее."],  
["neither", "ни один, ни другой", "Neither of the options is suitable.", "Ни один из вариантов не подходит."],  
["noise", "шум", "The noise from the construction was very loud.", "Шум от строительства был очень громким."],  
["none", "никто; ничто", "None of the students knew the answer.", "Никто из студентов не знал ответ."],  
["offer", "предложение", "He made an offer to buy the house.", "Он сделал предложение купить дом."],  
["onto", "на (поверхность)", "She jumped onto the platform.", "Она прыгнула на платформу."],  
["opportunity", "возможность", "This job offers a great opportunity for growth.", "Эта работа предоставляет отличную возможность для роста."],  
["ordinary", "обычный", "It was just an ordinary day at work.", "Это был просто обычный день на работе."],  
["organize", "организовать", "She will organize the meeting for next week.", "Она организует встречу на следующую неделю."],  
["ourselves", "сами", "We will have to do it ourselves.", "Нам придется сделать это сами."],  
["oven", "духовка", "The cake is baking in the oven.", "Торт печется в духовке."],  
["pack", "упаковывать", "I need to pack my suitcase for the trip.", "Мне нужно упаковать чемодан для поездки."],  
["pain", "боль", "He felt a sharp pain in his leg.", "Он почувствовал острую боль в ноге."],  
["painter", "художник", "The painter created a beautiful landscape.", "Художник создал красивый пейзаж."],  
["palace", "дворец", "The royal family lives in a large palace.", "Королевская семья живет в большом дворце."],  
["pants", "брюки", "He wore a pair of blue pants to the meeting.", "Он надел синие брюки на встречу."],  
["parking", "парковка", "There is limited parking near the restaurant.", "Возле ресторана ограниченная парковка."],  
["particular", "особенный", "She has a particular interest in history.", "Она имеет особый интерес к истории."],

["patient", "пациент; терпеливый", "The patient is waiting for the doctor.", "Пациент ждет врача."],  
["pass", "проходить; сдавать", "He passed the exam with high marks.", "Он сдал экзамен с высокими оценками."],  
["patient", "пациент; терпеливый", "You need to be patient during the process.", "Тебе нужно быть терпеливым в процессе."],  
["penny", "пенни", "She found a penny on the ground.", "Она нашла монету на земле."],  
["per", "за (единицу)", "The price is $10 per ticket.", "Цена составляет 10 долларов за билет."],  
["per cent", "процент", "The discount is 20 per cent off.", "Скидка составляет 20 процентов."],  
["perform", "выступать; выполнять", "The band will perform at the concert tonight.", "Группа выступит на концерте этой ночью."],  
["petrol", "бензин", "The car needs more petrol.", "Машине нужно больше бензина."],  
["pick", "выбирать", "She will pick a book from the shelf.", "Она выберет книгу с полки."],  
["pleased", "довольный", "He was pleased with his results.", "Он был доволен своими результатами."],  
["pocket", "карман", "He put his keys in his pocket.", "Он положил свои ключи в карман."],  
["polite", "вежливый", "She is always polite to everyone.", "Она всегда вежлива со всеми."],  
["pollution", "загрязнение", "Air pollution is a major issue in many cities.", "Загрязнение воздуха — это важная проблема во многих городах."],  
["possession", "владение", "The car is his possession.", "Машина — его собственность."],  
["predict", "предсказывать", "It’s hard to predict the weather tomorrow.", "Трудно предсказать погоду на завтра."],  
["prevent", "предотвращать", "Regular exercise can prevent many health issues.", "Регулярные физические упражнения могут предотвратить многие проблемы со здоровьем."],  
["prison", "тюрьма", "He was sent to prison for five years.", "Он был отправлен в тюрьму на пять лет."],

["prize", "приз", "She won a prize for her excellent performance.", "Она выиграла приз за отличные результаты."],  
["pull", "тянуть", "He had to pull the door to open it.", "Ему нужно было потянуть за дверь, чтобы открыть её."],  
["purpose", "цель", "The purpose of this meeting is to discuss the project.", "Цель этой встречи — обсудить проект."],  
["quietly", "тихо", "She spoke quietly so no one could hear.", "Она говорила тихо, чтобы никто не услышал."],  
["railway", "железная дорога", "The train travels along the railway tracks.", "Поезд едет по железнодорожным путям."],  
["raise", "поднимать", "She raised her hand to ask a question.", "Она подняла руку, чтобы задать вопрос."],  
["rate", "ставка; оценка", "The hotel has a high rate for its services.", "У отеля высокая ставка за услуги."],  
["rather", "скорее", "I would rather stay at home today.", "Я бы скорее остался дома сегодня."],  
["realize", "осознавать", "I just realized that I forgot my keys.", "Я только что осознал, что забыл свои ключи."],  
["receive", "получать", "I will receive the package tomorrow.", "Я получу посылку завтра."],  
["recent", "недавний", "There was a recent change in the schedule.", "Было недавнее изменение в расписании."],  
["recently", "недавно", "She recently moved to a new city.", "Она недавно переехала в новый город."],  
["reception", "прием; стойка регистрации", "The reception is on the first floor.", "Стойка регистрации на первом этаже."],  
["reduce", "уменьшать", "We need to reduce our energy consumption.", "Нам нужно уменьшить потребление энергии."],  
["refuse", "отказывать", "They refused to answer any more questions.", "Они отказались отвечать на дополнительные вопросы."],  
["respond", "отвечать", "He didn't respond to my email.", "Он не ответил на мое письмо."],  
["ring", "кольцо; звонить", "She wore a beautiful ring on her finger.", "Она носила красивое кольцо на пальце."],

["route", "маршрут", "This is the shortest route to the station.", "Это самый короткий маршрут до станции."],  
["rubbish", "мусор", "Please take the rubbish out.", "Пожалуйста, вынеси мусор."],  
["rude", "грубый", "His rude behavior upset everyone.", "Его грубое поведение расстроило всех."],  
["sadly", "печально", "She sadly looked at the empty room.", "Она печально посмотрела на пустую комнату."],  
["sail", "плавать на паруснике", "They will sail across the ocean next year.", "Они будут плавать через океан в следующем году."],  
["sailing", "парусный спорт", "Sailing is a popular activity in coastal areas.", "Парусный спорт — популярное занятие в прибрежных районах."],  
["salary", "зарплата", "He receives his salary at the end of the month.", "Он получает свою зарплату в конце месяца."],  
["sauce", "соус", "She added some tomato sauce to the pasta.", "Она добавила немного томатного соуса к пасте."],  
["scared", "испуганный", "He was scared of the dark.", "Он боялся темноты."],  
["scary", "страшный", "The movie was really scary.", "Фильм был действительно страшным."],  
["score", "оценка; счет", "The score of the game was 3-2.", "Счет игры был 3-2."],  
["seat", "место", "Please take a seat and wait for your turn.", "Пожалуйста, сядьте и ждите своей очереди."],  
["secondly", "во-вторых", "Secondly, we need to discuss the budget.", "Во-вторых, нам нужно обсудить бюджет."],  
["secretary", "секретарь", "The secretary will arrange the meeting.", "Секретарь организует встречу."],  
["seem", "казаться", "He seems to be a very kind person.", "Он кажется очень добрым человеком."],  
["sense", "чувство; смысл", "She has a great sense of humor.", "У нее отличное чувство юмора."],  
["serve", "обслуживать", "The waiter will serve the food shortly.", "Официант скоро подаст еду."],  
["shake", "пожимать; трясти", "They shook hands after the meeting.", "Они пожали руки после встречи."],  
["shall", "должен (формально)", "We shall meet at 5 PM.", "Мы встретимся в 5 вечера."],  
["shape", "форма", "The cake was in the shape of a heart.", "Торт был в форме сердца."],  
["sheet", "простыня; лист", "I need to change the bed sheet.", "Мне нужно сменить простыню."],  
["shoulder", "плечо", "She hurt her shoulder while lifting weights.", "Она повредила плечо, поднимая тяжести."],  
["shout", "кричать", "He had to shout to get their attention.", "Ему пришлось кричать, чтобы привлечь их внимание."],  
["shut", "закрыть", "Please shut the door when you leave.", "Пожалуйста, закройте дверь, когда уходите."],  
["sign", "знак", "There was a sign indicating the direction.", "Был знак, указывающий направление."],

["silver", "серебро", "She wore a necklace made of silver.", "Она носила ожерелье из серебра."],  
["since", "с тех пор как", "I haven't seen him since last week.", "Я не видел его с прошлой недели."],  
["singing", "пение", "She loves singing in the choir.", "Она любит петь в хоре."],  
["ski", "лыжа", "He bought a new pair of skis.", "Он купил новые лыжи."],  
["skiing", "катание на лыжах", "Skiing is popular in the winter season.", "Катание на лыжах популярно зимой."],  
["society", "общество", "Society has become more digital in recent years.", "Общество стало более цифровым за последние годы."],  
["sock", "носка", "He lost one of his socks in the laundry.", "Он потерял одну из своих носок в стирке."],  
["stage", "сцена", "The actors performed on stage.", "Актеры выступали на сцене."],  
["stair", "ступенька", "She slipped on the last stair.", "Она поскользнулась на последней ступеньке."],  
["steal", "красть", "He was caught trying to steal a car.", "Его поймали, когда он пытался украсть машину."],  
["straight", "прямой", "She walked in a straight line.", "Она шла по прямой линии."],  
["succeed", "добиваться успеха", "If you work hard, you will succeed.", "Если ты будешь работать усердно, ты добьешься успеха."],  
["successful", "успешный", "She became a successful businesswoman.", "Она стала успешной бизнесвумен."],  
["suggest", "предлагать", "I suggest we take a break.", "Я предлагаю сделать перерыв."],  
["suggestion", "предложение", "Do you have any suggestions for the project?", "У тебя есть предложения по проекту?"],  
["suit", "костюм; подходить", "This suit looks great on you.", "Этот костюм отлично на тебе сидит."],  
["suppose", "предполагать", "I suppose we can try it tomorrow.", "Я предполагаю, что мы можем попробовать это завтра."],  
["surprised", "удивленный", "He was surprised by the news.", "Он был удивлен новостью."],  
["surprising", "удивительный", "Her surprising victory shocked everyone.", "Ее удивительная победа потрясла всех."],  
["survey", "опрос", "They conducted a survey about consumer habits.", "Они провели опрос о потребительских привычках."],  
["themselves", "сами", "They did the project by themselves.", "Они сделали проект сами."],  
["thick", "толстый", "The book is too thick to carry around.", "Книга слишком толстая, чтобы носить её с собой."],

["thief", "вор", "The thief stole the wallet from the table.", "Вор украл кошелек со стола."],  
["thin", "тонкий", "She wore a thin sweater on the cold day.", "Она надела тонкий свитер в холодный день."],  
["thinking", "размышление", "His thinking was very logical and clear.", "Его размышления были очень логичными и ясными."],  
["thought", "мысль", "That was a great thought you had!", "Это была отличная мысль!"],  
["tidy", "опрятный", "Keep your room tidy and clean.", "Держи свою комнату в порядке и чистоте."],  
["tie", "галстук; связывать", "He wore a red tie to the meeting.", "Он надел красный галстук на встречу."],  
["tip", "совет; чаевые", "She gave a tip to the waiter.", "Она дала чаевые официанту."],  
["tour", "тур", "They went on a guided tour of the museum.", "Они отправились на экскурсию по музею."],  
["towards", "к", "She walked towards the exit.", "Она шла к выходу."],  
["truck", "грузовик", "The truck was loaded with goods.", "Грузовик был загружен товарами."],  
["twin", "близнец", "They are identical twins.", "Они идентичные близнецы."],  
["valley", "долина", "The village is located in a beautiful valley.", "Деревня расположена в красивой долине."],  
["van", "фургон", "The van delivered the furniture to our house.", "Фургон доставил мебель в наш дом."],  
["variety", "разнообразие", "There is a wide variety of fruits in the market.", "На рынке есть большое разнообразие фруктов."],  
["weak", "слабый", "He felt weak after the long illness.", "Он чувствовал себя слабым после долгой болезни."],  
["wet", "мокрый", "My shoes got wet in the rain.", "Мои ботинки промокли под дождем."],  
["wheel", "колесо", "The bicycle has two wheels.", "У велосипеда два колеса."],  
["whole", "целый", "She ate the whole cake.", "Она съела весь торт."],  
["whose", "чей", "Do you know whose book this is?", "Ты знаешь, чья это книга?"],  
["wide", "широкий", "The street is very wide.", "Улица очень широкая."],  
["wild", "дикой", "He saw a wild animal in the forest.", "Он увидел дикое животное в лесу."],  
["wooden", "деревянный", "The house has a beautiful wooden floor.", "В доме красивый деревянный пол."],  
["worried", "обеспокоенный", "She was worried about the test results.", "Она была обеспокоена результатами теста."],  
["worse", "хуже", "His condition got worse after the accident.", "Его состояние ухудшилось после аварии."],  
["worst", "худший", "This is the worst movie I have ever seen.", "Это худший фильм, который я когда-либо видел."],  
["yours", "твой", "The book is yours.", "Книга твоя."]              



	
];